Repository ddiniz-m/minishell, pull requests merged in 2023-10, with the labels that each got.

#51 Exit
  inc/minishell.h
  libft/src/ft_strjoin.c
  libft/src/ft_strlen.c
  src/built-ins/exit.c
  src/main.c
  src/parser/parse.c
  src/signals.c
  src/utils/frees.c
Labels: enhancement

#61 Pipeline behavior of `cd()` and `ft_exit()`
  Makefile
  inc/minishell.h
  src/built-ins/cd.c
  src/built-ins/exit.c
  src/built-ins/export.c
  src/built-ins/unset.c
  src/error_handling/errors.c
  src/error_handling/syntax_errors.c
  src/error_handling/syntax_errors2.c
  src/exec/exec.c
  src/exec/exec_built_ins.c
  src/exec/exec_utils.c
  src/exec/redir_hdoc.c
  src/exec/run_pipes.c
  src/frees.c
  src/main.c
  src/structs/cmd_utils.c
  src/structs/content.c
  src/structs/init.c
  src/utils/array_utl.c
  src/utils/env_utl.c
  src/utils/list_utl.c
  src/utils/str_utl.c
Labels: enhancement, help wanted, norm fix

#50 cd Fix
  inc/minishell.h
  src/built-ins/cd.c
  src/built-ins/export.c
  src/built-ins/pwd.c
  src/built-ins/unset.c
  src/error_handling/syntax_errors.c
  src/exec/exec_utils.c
  src/utils/env_utl.c
  src/utils/str_utl.c
Labels: bug, enhancement

#66 Pipex overhaul
  Makefile
  inc/minishell.h
  src/built-ins/exit.c
  src/built-ins/export.c
  src/built-ins/unset.c
  src/exec/exec.c
  src/exec/exec_utils.c
  src/exec/run_pipes.c
  src/main.c
  src/parser/parse.c
  src/parser/parse_counter.c
  src/parser/parse_split.c
  src/parser/parse_str.c
  src/run/exec.c
  src/run/exec_built_ins.c
  src/run/heredoc.c
  src/run/redirections.c
  src/run/run.c
  src/structs/init.c
  src/utils/array_utl.c
Labels: bug, enhancement, norm fix

#72 Export/Env fix
  src/built-ins/env.c
  src/built-ins/export.c
Labels: bug

#65 Echo and Replacer
  Makefile
  gnl/gnl.h
  inc/minishell.h
  libft/src/ft_isalpha.c
  libft/src/ft_strchr.c
  libft/src/ft_strdup.c
  libft/src/ft_strtrim.c
  src/built-ins/cd.c
  src/built-ins/echo.c
  src/built-ins/env.c
  src/built-ins/exit.c
  src/built-ins/export.c
  src/built-ins/unset.c
  src/error_handling/errors.c
  src/error_handling/syntax_errors.c
  src/error_handling/syntax_errors2.c
  src/frees.c
  src/main.c
  src/parser/parse_split.c
  src/parser/parse_str.c
  src/replacer/replacer.c
  src/replacer/replacer_split.c
  src/replacer/replacer_utl.c
  src/run/exec.c
  src/run/exec_built_ins.c
  src/run/redirections.c
  src/run/run.c
  src/signals.c
  src/structs/cmd_utils.c
  src/structs/content.c
  src/structs/init.c
  src/utils/env_utl.c
  src/utils/list_utl.c
  src/utils/quote_utl.c
  src/utils/str_utl.c
Labels: bug, enhancement

#75 Double prompt
  inc/minishell.h
  src/built-ins/cd.c
  src/built-ins/export.c
  src/main.c
  src/run/exec.c
  src/run/exec_built_ins.c
  src/run/heredoc.c
  src/run/redirections.c
  src/run/run.c
  src/signals.c
  src/structs/content.c
Labels: bug

#87 Fixed memory leak on is_exec
  src/run/cmd_validator.c
  src/run/exec.c
  src/structs/cmd_utils.c
  src/structs/content.c
Labels: bug, norm fix

#88 Fixed `''` error
  src/run/exec.c
  src/structs/init.c
Labels: bug
